# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3361510855a1559882c808c1132ae68a3f2990b1c76f0a449f0f64b89926f66d192d7c59fd5894a776077f582a1db171607833c8fae70ccca750df6b51eb4c4b

test:
  secret_key_base: e56169594f0a72f65d7269d7fdaae4afd9c5bb5b61344165dd0d6980ab8d7cd19184b88bf655c310cebcc055dd5cdb6a56a578555cf119390a8f605d5122a2cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
